### PR TITLE
Updated for python 3, craigslist post changes

### PR DESCRIPTION
**Pull request by atjeff**
Craigslist added a few new options to their "post" page, updated.

### CODE REVIEW

**Comment by notmike101** [comment]
Just to keep the python2.7 version alive, I've created a new branch for python3.
Go ahead and submit the pull request to that branch instead and I'll go ahead and merge it.

**Comment by atjeff** [comment]
I'll probably get to it tomorrow night.

**Comment by notmike101** [comment]
Hey, following up on this.  Did you still want me to pull your code?

**Comment by atjeff** [comment]
Yeah, please

**Comment by notmike101** [comment]
@atjeff If you can, go ahead and do a pull request on the python3 branch.  I've got no way of forcing it to that branch from my end.

**Pull request closed without merging**
